// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgtt7btM6e4ZjXx-bYO4NTrY4Dde5j-bc',
    appId: '1:37515243494:web:de6b75cf658b2a6bc67027',
    messagingSenderId: '37515243494',
    projectId: 'siyas-aqi-project',
    authDomain: 'siyas-aqi-project.firebaseapp.com',
    storageBucket: 'siyas-aqi-project.firebasestorage.app',
    measurementId: 'G-4KBPELRLQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiSplMGtNy39lLr9VKGstEB_Uo1gTkFNU',
    appId: '1:37515243494:android:3dd586e0c9461b4ac67027',
    messagingSenderId: '37515243494',
    projectId: 'siyas-aqi-project',
    storageBucket: 'siyas-aqi-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByUDUtyMMiz9jHlCDKWr5WoJQA01_Rtmw',
    appId: '1:37515243494:ios:aa2aa189165516a6c67027',
    messagingSenderId: '37515243494',
    projectId: 'siyas-aqi-project',
    storageBucket: 'siyas-aqi-project.firebasestorage.app',
    iosBundleId: 'com.example.vayu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByUDUtyMMiz9jHlCDKWr5WoJQA01_Rtmw',
    appId: '1:37515243494:ios:aa2aa189165516a6c67027',
    messagingSenderId: '37515243494',
    projectId: 'siyas-aqi-project',
    storageBucket: 'siyas-aqi-project.firebasestorage.app',
    iosBundleId: 'com.example.vayu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgtt7btM6e4ZjXx-bYO4NTrY4Dde5j-bc',
    appId: '1:37515243494:web:d5a72e580a97ed2ac67027',
    messagingSenderId: '37515243494',
    projectId: 'siyas-aqi-project',
    authDomain: 'siyas-aqi-project.firebaseapp.com',
    storageBucket: 'siyas-aqi-project.firebasestorage.app',
    measurementId: 'G-4F9GV9NMFX',
  );
}
