import 'package:equatable/equatable.dart';

/// A personalized recovery plan generated by the AI Coach.
class RecoveryPlan extends Equatable {
  const RecoveryPlan({
    required this.id,
    required this.generatedAt,
    required this.triggerExposureScore,
    required this.activities,
    required this.summary,
    required this.longTermRecommendations,
    this.expiresAt,
  });

  final String id;
  final DateTime generatedAt;
  final double triggerExposureScore;
  final List<RecoveryActivity> activities;
  final String summary;
  final List<String> longTermRecommendations;
  final DateTime? expiresAt;

  bool get isExpired =>
      expiresAt != null && DateTime.now().isAfter(expiresAt!);

  @override
  List<Object?> get props => [id, generatedAt, triggerExposureScore];
}

/// A single activity within a recovery plan.
class RecoveryActivity extends Equatable {
  const RecoveryActivity({
    required this.title,
    required this.description,
    required this.durationMinutes,
    required this.category,
    required this.priority,
    this.indoorAlternative,
    this.optimalTimeWindow,
  });

  final String title;
  final String description;
  final int durationMinutes;
  final ActivityCategory category;
  final int priority; // 1 = highest
  final String? indoorAlternative;
  final String? optimalTimeWindow;

  @override
  List<Object?> get props => [title, category, priority];
}

enum ActivityCategory {
  breathing(label: 'Breathing Exercise', icon: '🫁'),
  hydration(label: 'Hydration', icon: '💧'),
  indoorExercise(label: 'Indoor Exercise', icon: '🏋️'),
  airPurification(label: 'Air Purification', icon: '🌬️'),
  nutrition(label: 'Nutrition', icon: '🥗'),
  rest(label: 'Rest', icon: '😴'),
  outdoorTiming(label: 'Outdoor Timing', icon: '⏰');

  const ActivityCategory({required this.label, required this.icon});
  final String label;
  final String icon;
}
